### ISSUE TITLE
[Bug]: Homepage icon wrapper and text not centered

### ISSUE THREAD

**Issue by quarkquartet** [edelvarden/material-fox-updated#101]
### What happened?

<img width="843" alt="image" src="https://github.com/user-attachments/assets/be5e6086-65f3-440f-884d-867be969561e" />

I've been using this for years and this is the first day for this issue to happen.

I have edited the `user-content.css` to modify the icon wrapper size years ago to make the icon larger. That has been working perfectly for years and I don't think that will cause this issue. But today as can be seen from the figure, the text and icon wrapper is not centered with the icon.

Since this issue never happened before with my editing, I suspect that is caused by some recent firefox update.

### Steps to reproduce

1. Download the release.
2. Open `user-content.css`.
3. Edit the following piece:
```css
.top-site-outer .tile {
            border-radius: 100px !important;
            height: 84px !important;
            width: 84px !important;
            box-shadow: none !important
        }
 .top-site-outer .tile .icon-wrapper {
            border-radius: 60px !important;
            width: 60px !important;
            height: 60px !important
        }
```
Compare to the original code, the only thing I have changed is the number of px.
4. Install following the guide and run firefox.

### Additional info (Optional)

Firefox version: 134.0
MacOS version: 15.2

**Comment by quarkquartet** [comment]
So far a temporary solution
```css
.top-site-outer {
        display: flex !important;
        justify-content: center !important;
        align-items: center !important;
    }
```
If this is indeed the best solution, just add it.
