### ISSUE TITLE
[Bug]: You can't see the download progress bar because of the backgroud color

### ISSUE THREAD

**Issue by Zap-09** [edelvarden/material-fox-updated#104]
### What happened?

<img width="419" alt="Image" src="https://github.com/user-attachments/assets/ec1a6e69-1036-4704-8c4a-c70371d560e8" />

So I was wandering if there is a way to change the color of the background?

### Steps to reproduce

Not needed

### Additional info (Optional)

FireFox Version: 135.0 (64-bit)
OS: Windows 10

**Comment by kbc8090** [comment]
Here's what I did for that:

```css
#downloadsListBox:focus > richlistitem[selected] {
  .downloadProgress::-moz-progress-bar {
    --download-progress-fill-color: color-mix(in srgb, var(--md-background-color-0) 60%, var(--md-accent-color)) !important;
  }
}
```
