### ISSUE TITLE
[Bug]: Duplicated tab sound indicator as of Firefox version 136

### ISSUE THREAD

**Issue by ItsPasi** [edelvarden/material-fox-updated#106]
### What happened?

A new sound indicator is now shown in tabs.

![Image](https://github.com/user-attachments/assets/3bf2c695-ca9e-4f1a-8383-99e7a959f2fb)

### Steps to reproduce

1. Open a tab with sound
2. See 2 sound indicators

### Additional info (Optional)

Firefox Version: 136.0b9
Windows 11

**Comment by PeopleInside** [comment]
![Image](https://github.com/user-attachments/assets/2d43c9b5-8da9-46cf-bdcf-28239bb2b63e)

Firefox 136.0b9 (64 bit)

Issue also on the stable Firefox 135.0.1 https://github.com/edelvarden/material-fox-updated/issues/107

**Comment by kbc8090** [comment]
Here's what I'm using, but I have extensive mods to Material Fox Updated that I use. This gets rid of the double sound indicators though.

```css
  .tab-audio-button {
        display: none !important;
  }

  :is(.all-tabs-secondary-button, .tab-icon-overlay)[soundplaying],
  .tab-icon-sound {
    -moz-context-properties: fill, fill-opacity !important;
    list-style-image: url("icons/audio.svg") !important;
    fill-opacity: 1 !important;
    fill: var(--md-text-primary) !important;
    background-color: transparent !important;
    border: 0px !important;
  }

  .all-tabs-secondary-button,
  .tab-icon-overlay,
  .tab-icon-sound {
    &[muted] {
      -moz-context-properties: fill, fill-opacity !important;
      list-style-image: url("icons/audio-muted.svg")  !important;
      fill-opacity: 1 !important;
      fill: var(--md-text-secondary) !important;
      border: 0px !important;
      background-color: transparent !important;
    }
  }

  .all-tabs-secondary-button,
  .tab-icon-overlay,
  .tab-icon-sound {
    &[activemedia-blocked] {
      -moz-context-properties: fill, fill-opacity !important;
      list-style-image: url("icons/audio-muted.svg")  !important;
      fill-opacity: 1 !important;
      fill: var(--md-text-secondary) !important;
      border: 0px !important;
      background-color: transparent !important;
    }
  }
```
