### ISSUE TITLE
[Bug]: Duplicated Website Info/Cookies Button

### ISSUE THREAD

**Issue by Halilman04** [edelvarden/material-fox-updated#110]
### What happened?

The cookies and security tab is here twice in the search bar (not exactly the same button but it's the same icon). I noticed it does't happen everywhere, but google website and my schools website have it. I don't use either of them but i am really annoyed by inconsistency.

How it looks:
![Image](https://github.com/user-attachments/assets/c792bdd2-548a-4358-b51c-04eaf9097966)

### Steps to reproduce

1. Open firefox
2. Go to any secured website like youtube or gmail

### Additional info (Optional)

Firefox 136.0.1
Windows 11 23h2

**Comment by randomguy-2650** [comment]
I think that’s a Firefox‐specific issue as CSS alone can’t move specific elements from specific menus to another menu. You can only fix it by changing the Firefox UI’s HTML and XUL, which is impossible to do in an installation of Firefox without building it from its source code.

**Comment by kbc8090** [comment]
I worked on something to hide that #identity-permission-box until the #identity-box is hovered then it slides out.  I find it to be a cleaner look, feel free to use:

```css

#identity-permission-box {

  #urlbar & {
    margin-inline-start: -24px !important;
    opacity: 0 !important;
    transition: margin-inline-start 130ms cubic-bezier(0, 0, 0.2, 1) 500ms, opacity 30ms ease 500ms !important;
  }

  #urlbar:has(#identity-box:not(.chromeUI):hover) &,
  #urlbar:has(#identity-box:not(.chromeUI):active) &,
  #urlbar:has(#identity-box:not(.chromeUI):focus-within) &,
  #urlbar:has(#identity-box:not(.chromeUI):focus) &,
  #urlbar:has(#identity-box[open="true"]:not(.chromeUI)) &,
  #urlbar:has(#identity-icon:not(.chromeUI):hover) &,
  #urlbar:has(#identity-icon:not(.chromeUI):active) &,
  #urlbar:has(#identity-icon:not(.chromeUI):focus-within) &,
  #urlbar:has(#identity-icon:not(.chromeUI):focus) &,
  #urlbar:has(#identity-icon[open="true"]:not(.chromeUI)) &,
  #urlbar:has(#identity-icon-box:not(.chromeUI):hover) &,
  #urlbar:has(#identity-icon-box:not(.chromeUI):active) &,
  #urlbar:has(#identity-icon-box:not(.chromeUI):focus-within) &,
  #urlbar:has(#identity-icon-box:not(.chromeUI):focus) &,
  #urlbar:has(#identity-icon-box[open="true"]:not(.chromeUI)) &,
  #urlbar &:hover:active,
  #urlbar &[open="true"],
  #urlbar &:focus-within {
    margin-inline-start: 2px !important;
    opacity: 1 !important;
    transition: margin-inline-start 130ms cubic-bezier(0, 0, 0.2, 1) 60ms, opacity 180ms ease 60ms !important;
  }
}

```
