### ISSUE TITLE
[Bug]: “Not secure” doesn’t fit into pill shape correctly (Chrome Refresh 2023)

### ISSUE THREAD

**Issue by randomguy-2650** [edelvarden/material-fox-updated#118]
### What happened?

Here, you can see that the text “Not secure” and its icon touches the edge of the pill. I don’t think this was intended, because it doesn’t happen for all other things that take place in this pill (like “Firefox”). This happens if `userChrome.ui-chrome-refresh` is enabled.

**Screenshots:**

![Image](https://github.com/user-attachments/assets/ee26c630-d059-49e4-86fb-b10c4dbcdbd4)

### Steps to reproduce

1. Open Firefox and go to a site that doesn’t support HTTPS
2. Follow the warnings to visit the site (i.e. ignoring the warnings)
3. Looking at the pill shape in the address bar

### Additional info (optional)

Firefox version: 138.0, but also older versions as well
Operating system: Irrelevant, is a `user-chrome.css` problem

**Comment by kbc8090** [comment]
Could just hide it with:

``` css
#identity-box[pageproxystate="valid"]:is(.notSecure, .notSecureText, .mixedActiveContent, .httpsOnlyErrorPage, .weakCipher, .mixedDisplayContent, .mixedDisplayContentLoadedActiveBlocked, .certUserOverridden, #identity-box[pageproxystate="valid"].certErrorPage) #identity-icon-label {
  display: none !important;
}

```

**Comment by randomguy-2650** [comment]
There is a similar issue with this closed PR though: https://github.com/edelvarden/material-fox-updated/pull/80.

**Comment by kbc8090** [comment]
``` css
#identity-box[pageproxystate="valid"]:is(.extensionPage, .notSecure, .notSecureText, .mixedActiveContent, .httpsOnlyErrorPage, .weakCipher, .mixedDisplayContent, .mixedDisplayContentLoadedActiveBlocked, .certUserOverridden, #identity-box[pageproxystate="valid"].certErrorPage) #identity-icon-box.identity-box-button {
    padding-inline: 8px !important;
}
```
