### ISSUE TITLE
[Bug]: Background when right clicking

### ISSUE THREAD

**Issue by BigOxy** [edelvarden/material-fox-updated#122]
### What happened?

![Image](https://github.com/user-attachments/assets/94101858-8fa6-4fd5-bbd9-c5a5ad001029)

Firefox version 138.0
When right clicking, a background appears for the menu

### Steps to reproduce

1. Open Fierfox
2. 2. Right Click anywhere on ths screen

**Comment by randomguy-2650** [comment]
I can confirm that this is an issue. I found a fix though. To fix it, you have to apply this to your `custom.css`:

```CSS
@media (-moz-platform: windows) {
    menupopup,
    panel:not(#autoscroller) {
        --panel-shadow-margin: 0 !important;
    }
}
```

I’ll also write a pull request to fix this.

![Screenshot of context menu in Firefox with userChrome theme applied](https://github.com/user-attachments/assets/0156128f-10c1-4aab-9ac7-fd0c6acc4273)
