### ISSUE TITLE
[Bug]: Inconsistancy of padding and spacement on the top bar

### ISSUE THREAD

**Issue by TheDogHusky** [edelvarden/material-fox-updated#132]
### What happened?

The top panel has inconsistent paddings and spacings:
- Top left icon for the "list all tabs button" is not vertically centered (by one or two pixels) (screenshot one)
- "+" icon has too much padding on the left, and is a little too big compared to the tabs (by two or one pixel) (screenshot two)
- url bar icons does not have the same size when hovered (screenshots left)

![Image](https://github.com/user-attachments/assets/4789814a-ced7-4e08-a82d-868cc75e3d3d)

![Image](https://github.com/user-attachments/assets/3d12e382-1917-4761-920b-bfa5a09ea7a1)

![Image](https://github.com/user-attachments/assets/d0c5469c-c7f1-4009-853f-266934a07265)

![Image](https://github.com/user-attachments/assets/c1903e32-80b5-4758-ab04-f41df8b48546)

### Steps to reproduce

1. Install material fox
2. Enable refresh UI
3. See for yourself

### Additional info (Optional)

FF version: 138.0.4
OS: Arch Linux
Material Fox UPDATED: 2.0.0

**Comment by TheDogHusky** [comment]
Additional issue:
Pinned tabs have extra width on the right:

![Image](https://github.com/user-attachments/assets/2bbdc6c8-5a1b-482a-8000-b9dc8cc13d46)

**Comment by kbc8090** [comment]
I have all this fixed in mine since I noticed all the same issues.  Can check out my personal.css file in my firefox repository if you want to dig thru all the changes.  Also before chrome removed the alltabs button they changes all the border-radius's to 10px I noticed rather than 11, so I have that in there too.

Franky I'm just too lazy to submit proper PR's and submit portions of code for something only a handful people would ever know or care about.

![Image](https://github.com/user-attachments/assets/ee12e14c-1a56-40d3-886f-645e561c0b28)

**Comment by TheDogHusky** [comment]
Well, with your permissions, i'll gladly make a PR for this

**Comment by kbc8090** [comment]
Sure man, go for it, the code in that file is pretty messy and spread out and not fully commented but it works for me.

**Comment by TheDogHusky** [comment]
Well, yea, i'm tryna grab the parts that fixes the issues, but i'm struggling to find the part for the tab list (found for the spacing), and new tab button size, and toolbar button inconsistency especially for the extensions button)

**Comment by kbc8090** [comment]
Anything related to the tablist should be under anything related to the alltabs-button.

I just use "userChrome.ui-force-old-icons" to true fix the extension thing.

**Comment by TheDogHusky** [comment]
Oh yep I did find all the fixes, thanks !

**Comment by kbc8090** [comment]
fwiw you can also just use this to keep the same size extension button.

```css
#unified-extensions-button>image {
  transform: unset !important;
}
```

**Comment by kbc8090** [comment]
This is mega unrelated but if for some reason in Chrome you want to restore that alltabs button to the normal location, for now you can set: chrome://flags/#tabstrip-combo-button to DISABLED

**Comment by kbc8090** [comment]
another thing is the 2px wide tab separator is mis-aligned in "chrome-refresh" so I fixed that.

```css
/* Tab separator moved 1px left for chrome since it was mis-aligned */
.tab-content {
  overflow: visible !important;
    &::before,
    &::after {
      @media (-moz-pref("userChrome.ui-chrome-refresh")) {
        width: 2px !important;
        height: 16px !important;
        left: -1px !important;
      }
      @media not (-moz-pref("userChrome.ui-chrome-refresh")) {
        width: 1px !important;
        height: 18px !important;
        left: 0 !important;
      }
    }
}
```

**Comment by randomguy-2650** [comment]
If comparing with Chrome, the extension button actually has the correct size, all the other ones don’t.

**Comment by randomguy-2650** [comment]
> another thing is the 2px wide tab separator is mis-aligned in "chrome-refresh" so I fixed that.
> 
> ```CSS
> /* Tab separator moved 1px left for chrome since it was mis-aligned */
> .tab-content {
>   overflow: visible !important;
>     &::before,
>     &::after {
>       @media (-moz-pref("userChrome.ui-chrome-refresh")) {
>         width: 2px !important;
>         height: 16px !important;
>         left: -1px !important;
>       }
>       @media not (-moz-pref("userChrome.ui-chrome-refresh")) {
>         width: 1px !important;
>         height: 18px !important;
>         left: 0 !important;
>       }
>     }
> }
> ```

**Comment by TheDogHusky** [comment]
JUst saw that these buttons here in the searchbar are completely wrong: too big compared to chromium, unconsistent padding, etc..

sadly I have been struggling to fix it since somehow, the padding-top and padding-bottom properties seems to not work on those specific hboxes, leading to the impossibility to copy the code making the identity box even to here.

Even on chrome, it's pretty messed up..

![Image](https://github.com/user-attachments/assets/4a2aa71e-4441-4d70-b562-eaa9b11e2d7c)

![Image](https://github.com/user-attachments/assets/c779108a-0e16-47e0-91b6-3811c4cef79c)

**Comment by TheDogHusky** [comment]
my bad, i didn't mean to close it

**Comment by randomguy-2650** [comment]
> my bad, i didn't mean to close it

Then reopen the issue. It’s under the comment section.

**Comment by TheDogHusky** [comment]
Well, it was grayed out for a moment, thought I couldn't reopen it ahah

**Comment by kbc8090** [comment]
I fiddled with those a good bit and differing urlbar heights, compact/touch/normal, comparing to chrome, seeing what looked right but ended up just leaving it.  I have the zoom button sitting right to my eye so that's all that mattered.

**Comment by TheDogHusky** [comment]
I'm gonna upload my fixes to a css file on github until i have enough time to make a PR. I havent figured out the searchbar stuff yet but i guess i'll work it out somehow

**Comment by TheDogHusky** [comment]
https://github.com/TheDogHusky/materialfox-fixes/tree/main

**Comment by TheDogHusky** [comment]
i'm also pretty much annoyed by the fact that the transitions are completely different than in chromium

**Comment by TheDogHusky** [comment]
> fwiw you can also just use this to keep the same size extension button.
> 
> #unified-extensions-button>image {
>   transform: unset !important;
> }

regarding this, it makes the extension icon too small compared to the others

**Comment by TheDogHusky** [comment]
FIxed by doing this alongside the remove of the transform property:
```css
#unified-extensions-button > image {
  transform: unset !important;
  padding: calc(var(--toolbarbutton-inner-padding) - 2px) !important;
}
```

I don't know why they used a transform in the css instead of tweaking the padding to fix it.
