### ISSUE TITLE
[Bug]: Address Bar overlaps Tab Hover Dialog

### ISSUE THREAD

**Issue by elian-ow** [edelvarden/material-fox-updated#39]
### What happened?

![image](https://github.com/edelvarden/material-fox-updated/assets/135343836/5972e3e0-e784-4564-a7af-6802168905d4)
Title says it all

### Steps to reproduce the problem

1. Have the theme installed with the instructions
2. Hover over a tab

### Additional info (Optional)

Firefox version: Firefox Nightly 123.0a1 64-bit
Operating system: Windows 11 23H2

**Comment by edelvarden** [comment]
I'll wait until this goes to dev version.

As a temporary solution you can enable old tooltips with custom css if this is critical for you:

```css
#tabbrowser-tab-tooltip {
  display: flex !important;
}

.tabbrowser-tab::after {
  display: none !important;
}
```
