### ISSUE TITLE
[Feature Request]: Improve findbar appearance

### ISSUE THREAD

**Issue by ItsPasi** [edelvarden/material-fox-updated#74]
### Description

I have a few suggestions for a better findbar experience that also matches chrome more closely. For one the distance to the corner of the window should be increased by about 5-10px so it looks like it hovers in the corner.
For the second option I would like if a hover animation can be added to the text field similar to chrome where if you hover over it it gets highlighted by being slightly darker. Maybe also increase the shadow amount like in my example below.

I made the following code some time ago to achieve this, not sure which of it is still important and up to date but it should give a good idea.

**1st Suggestion:**
```
.browserContainer > findbar {
  position: absolute !important;
  top: 0 !important;
  bottom: 0 !important;
  right: 10px !important;
  margin: 10px 0rem 0 0 !important;
}
```
**2nd Suggestion:**
```
.findbar-textbox {
  height: 30px !important;
  background: transparent !important;
  border: none !important;
  outline: none !important;
}
.findbar-textbox {
  border-left: 0px solid !important;
  border-right: 1px solid !important;
  border-color: get-var("menu-border-color") !important;
  border-radius: 0 !important;
  transition-timing-function: get-var("point-to-point") !important;
  transition-duration: get-var("medium-duration") !important;
}
.findbar-textbox:hover{
  border-left: 0px solid !important;
  border-right: 0px solid !important;
  border-color: get-var("menu-border-color") !important;
  border-radius: 8px!important;
  background-color: get-var("background-color-50") !important;
}
.findbar-textbox:focus-visible{
  box-shadow: none !important;
}
```

**My Code Example:**

![grafik](https://github.com/user-attachments/assets/a360939a-b8d1-4f0f-be51-123ab0111cc8)

**Comment by edelvarden** [comment]
@ItsPasi, thank you for the detailed explanation and code examples. I will add this soon.

**Comment by zkisaboss** [comment]
There's minor flickering when you close the find bar

**Comment by ItsPasi** [comment]
Oh also I just checked out your implementation and I like it but I think the margin of 2px from the side is still a bit low. I would def prefer it to be 5-8px margin.


> There's minor flickering when you close the find bar

Yeah that would be nice to fix but isn't because of my code

**Comment by kbc8090** [comment]
Here's how I've edited mine... turns red on no matches, 17px from right so doenst get in the way of "style 1" scrollbars.  Also the close animation is slower so no flickering.

```css

  /* Adjusting find bar border/position */
  .browserContainer > findbar {
    margin: 2px 17px 0 0 !important;
  }

findbar {
  border: var(--md-menu-border-size) !important;
  border-color: var(--md-menu-border-color) !important;
  padding-left: 8px !important;

  &[hidden='true'] {
    animation: 0.5s findbar-scale-out;
  }
}

.findbar-textbox {
  &[status="notfound"] {
    background-color: rgba(255, 0, 0, 0.3) !important;
    border-color: transparent !important;
    border-radius: 4px !important;
  }
}

```
